# Generated by Django 5.0.6 on 2024-06-09 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('scripcode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
